apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adhanplayer
  namespace: adhanplayer
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: adhanplayer-adhanplayer-add-slash@kubernetescrd,adhanplayer-adhanplayer-strip@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: tinker
    http:
      paths:
      - path: /adhanplayer
        pathType: Prefix
        backend:
          service:
            name: adhanplayer
            port:
              number: 8000

